/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TodosIndexImport } from './routes/todos/index'
import { Route as TodosTodoIdIndexImport } from './routes/todos/$todoId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TodosIndexRoute = TodosIndexImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRoute,
} as any)

const TodosTodoIdIndexRoute = TodosTodoIdIndexImport.update({
  id: '/todos/$todoId/',
  path: '/todos/$todoId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosIndexImport
      parentRoute: typeof rootRoute
    }
    '/todos/$todoId/': {
      id: '/todos/$todoId/'
      path: '/todos/$todoId'
      fullPath: '/todos/$todoId'
      preLoaderRoute: typeof TodosTodoIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos': typeof TodosIndexRoute
  '/todos/$todoId': typeof TodosTodoIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos': typeof TodosIndexRoute
  '/todos/$todoId': typeof TodosTodoIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/todos/': typeof TodosIndexRoute
  '/todos/$todoId/': typeof TodosTodoIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos' | '/todos/$todoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos' | '/todos/$todoId'
  id: '__root__' | '/' | '/todos/' | '/todos/$todoId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosIndexRoute: typeof TodosIndexRoute
  TodosTodoIdIndexRoute: typeof TodosTodoIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosIndexRoute: TodosIndexRoute,
  TodosTodoIdIndexRoute: TodosTodoIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/todos/",
        "/todos/$todoId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/todos/": {
      "filePath": "todos/index.tsx"
    },
    "/todos/$todoId/": {
      "filePath": "todos/$todoId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
